version: '3'

services:
  db:
    image: postgres:16.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5439:5432'
    volumes:
      - ./src/main/resources/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql